### ISSUE TITLE
currently fails to build on openshift.com free tier

### ISSUE THREAD

**Issue by simbo1905** [openshift-s2i/s2i-aspnet-example#33]
I tried out this sample app using openshift free tier and it refused to build with: 

	Cloning "https://github.com/redhat-developer/s2i-dotnetcore-ex.git " ...
		Commit:	0543be02d0be779d08e6c43f82ef9f0610f5d4e3 (Update for .NET Core 2.0 release. (#32))
		Author:	Severin Gehwolf <jerboaa@gmail.com>
		Date:	Mon Aug 21 18:00:03 2017 +0200
	Pulling image "registry.access.redhat.com/dotnet/dotnet-20-rhel7@sha256:0dbafdca780475373a34be07877b152f94ff7ef4168758f1f9011bc71793245f" ...
	---> Copying application source ...
	error: DOTNET_STARTUP_PROJECT has no project file
	You can specify the startup project by adding an '.s2i/environment' file to the source repository.
	The source repository contains the following projects:
	- app/app.csproj
	Update the '.s2i/environment' file to specify the project you want to publish, for example DOTNET_STARTUP_PROJECT=app/app.csproj.
	error: build error: non-zero (13) exit code from registry.access.redhat.com/dotnet/dotnet-20-rhel7@sha256:0dbafdca780475373a34be07877b152f94ff7ef4168758f1f9011bc71793245f

**Comment by jerboaa** [comment]
@simbo1905 Can you be more specific, please? On OpenShift Online there is a wizard to try out .NET. Did you use that? Some `oc new-app` command? Thanks!

**Comment by simbo1905** [comment]
To reproduce:

1) sign up for a new openshift.com free account 
2) select ".net" from the new wizard they have as the landing page 
3) select the defaults which are 2.0 and building the source code for this repo
4) the build fails 

The fix was to install the image streams from this repo and create the app from the templates in this repo. The problem seems to be with the openshift free tier not keeping their templates up to date which links to this latest source code over here. As there is no support with free teir it's not clear how I tell them about their problem.

**Comment by jerboaa** [comment]
@simbo1905 Thanks for the report! Reproduced. I'll make sure appropriate steps are in place so a) this gets fixed and b) this won't happen again.

**Comment by jerboaa** [comment]
Something odd is going on. The imagestream definition on OSO has the correct `sampleRef` and `sampleContextDir` definitions:

    $ oc export -n openshift -o json is dotnet | grep -E 'sampleRef|sampleContextDir'
                "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"ImageStream\",\"metadata\":{\"annotations\":{\"openshift.io/display-name\":\".NET Core Builder Images\"},\"name\":\"dotnet\",\"namespace\":\"openshift\"},\"spec\":{\"tags\":[{\"annotations\":{\"description\":\"Build and run .NET Core applications on RHEL 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/redhat-developer/s2i-dotnetcore/tree/master/2.0/build/README.md.\\n\\nWARNING: By selecting this tag, your application will automatically update to use the latest version of .NET Core available on OpenShift, including major versions updates.\",\"iconClass\":\"icon-dotnet\",\"openshift.io/display-name\":\".NET Core (Latest)\",\"sampleContextDir\":\"app\",\"sampleRef\":\"dotnetcore-2.0\",\"sampleRepo\":\"https://github.com/redhat-developer/s2i-dotnetcore-ex.git\",\"supports\":\"dotnet\",\"tags\":\"builder,.net,dotnet,dotnetcore\"},\"from\":{\"kind\":\"ImageStreamTag\",\"name\":\"2.0\"},\"name\":\"latest\"},{\"annotations\":{\"description\":\"Build and run .NET Core 2.0 applications on RHEL 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/redhat-developer/s2i-dotnetcore/tree/master/2.0/build/README.md.\",\"iconClass\":\"icon-dotnet\",\"openshift.io/display-name\":\".NET Core 2.0\",\"sampleContextDir\":\"app\",\"sampleRef\":\"dotnetcore-2.0\",\"sampleRepo\":\"https://github.com/redhat-developer/s2i-dotnetcore-ex.git\",\"supports\":\"dotnet:2.0,dotnet\",\"tags\":\"builder,.net,dotnet,dotnetcore,rh-dotnet20\",\"version\":\"2.0\"},\"from\":{\"kind\":\"DockerImage\",\"name\":\"registry.access.redhat.com/dotnet/dotnet-20-rhel7:2.0\"},\"name\":\"2.0\"},{\"annotations\":{\"description\":\"Build and run .NET Core 1.1 applications on RHEL 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/redhat-developer/s2i-dotnetcore/tree/master/1.1/README.md.\",\"iconClass\":\"icon-dotnet\",\"openshift.io/display-name\":\".NET Core 1.1\",\"sampleContextDir\":\"app\",\"sampleRef\":\"dotnetcore-1.1\",\"sampleRepo\":\"https://github.com/redhat-developer/s2i-dotnetcore-ex.git\",\"supports\":\"dotnet:1.1,dotnet\",\"tags\":\"builder,.net,dotnet,dotnetcore,rh-dotnetcore11\",\"version\":\"1.1\"},\"from\":{\"kind\":\"DockerImage\",\"name\":\"registry.access.redhat.com/dotnet/dotnetcore-11-rhel7:1.1\"},\"name\":\"1.1\"},{\"annotations\":{\"description\":\"Build and run .NET Core 1.0 applications on RHEL 7. For more information about using this builder image, including OpenShift considerations, see https://github.com/redhat-developer/s2i-dotnetcore/tree/master/1.0/README.md.\",\"iconClass\":\"icon-dotnet\",\"openshift.io/display-name\":\".NET Core 1.0\",\"sampleContextDir\":\"app\",\"sampleRef\":\"dotnetcore-1.0\",\"sampleRepo\":\"https://github.com/redhat-developer/s2i-dotnetcore-ex.git\",\"supports\":\"dotnet:1.0,dotnet\",\"tags\":\"builder,.net,dotnet,dotnetcore,rh-dotnetcore10\",\"version\":\"1.0\"},\"from\":{\"kind\":\"DockerImage\",\"name\":\"registry.access.redhat.com/dotnet/dotnetcore-10-rhel7:1.0\"},\"name\":\"1.0\"}]}}\n",
                        "sampleContextDir": "app",
                        "sampleRef": "dotnetcore-1.0",
                        "sampleContextDir": "app",
                        "sampleRef": "dotnetcore-1.1",
                        "sampleContextDir": "app",
                        "sampleRef": "dotnetcore-2.0",
                        "sampleContextDir": "app",
                        "sampleRef": "dotnetcore-2.0",

For some reason current OpenShift does not seem to pick this up correctly. It's using branch `master` and context dir `/`, while it should be using `dotnetcore-2.0` and `app` respectively. We have a [test in place](https://github.com/redhat-developer/s2i-dotnetcore/blob/master/2.0/build/test/run#L492) which attempts to catch this, but it's using s2i directly with correct context dir and branch parameters. So this seems an issue on the OpenShift side for which I don't know there exists an automated test.

@simbo1905 The work-around for you is to go to "Builds => Builds", find the correct build name, and click the "Actions => Edit" button (top right). Then set references for the branch and context dir as shown here:
![screenshot from 2017-12-18 10-48-06](https://user-images.githubusercontent.com/357222/34100215-0ad8f360-e3e2-11e7-9473-e4621b0c50b5.png)

Pay specific attention to ***Git Reference*** and ***Context Dir*** fields. Click, "Save" and then "Start Build" (next to "Actions on the top right). Then everything should deploy properly.

I'll follow up with OpenShift folks separately about this issue.

**Comment by jerboaa** [comment]
@tmds @aslicerh FYI.

**Comment by jerboaa** [comment]
@simbo1905 FYI: I've filed https://bugzilla.redhat.com/show_bug.cgi?id=1527638 for this issue.

**Comment by tmds** [comment]
Closing old issues.
