### ISSUE TITLE
Openshift enterprise - dotnet - Operation not permitted errors

### ISSUE THREAD

**Issue by sriprasannafs** [openshift-s2i/s2i-aspnet-example#34]
Hello there. I am trying to build an asp.net application on our OpenShift enterprise platform. I am running into the following errors at the very end of the build process:

_chgrp: changing group of '/opt/app-root/src/..1981_10_01_05_57_36.162036423/.gitconfig': Operation not permitted
  | chgrp: changing group of '/opt/app-root/src/..1981_10_01_05_57_36.162036423/password': Operation not permitted
  | chgrp: changing group of '/opt/app-root/src/..1981_10_01_05_57_36.162036423/username': Operation not permitted
  | chgrp: changing group of '/opt/app-root/src/..1981_10_01_05_57_36.162036423': Operation not permitted
  | chgrp: changing group of '/opt/app-root/src/..data': Operation not permitted
  | chgrp: changing group of '/opt/app-root/src/.gitconfig': Operation not permitted
  | chgrp: changing group of '/opt/app-root/src/password': Operation not permitted
  | chgrp: changing group of '/opt/app-root/src/username': Operation not permitted
  | chmod: changing permissions of '/opt/app-root/src/..1981_10_01_05_57_36.162036423': Operation not permitted
  | chmod: changing permissions of '/opt/app-root/src/..1981_10_01_05_57_36.162036423/.gitconfig': Operation not permitted
  | chmod: changing permissions of '/opt/app-root/src/..1981_10_01_05_57_36.162036423/password': Operation not permitted
  | chmod: changing permissions of '/opt/app-root/src/..1981_10_01_05_57_36.162036423/username': Operation not permitted
  | chmod: changing permissions of '/opt/app-root/src/..1981_10_01_05_57_36.162036423': Operation not permitted
  | error: build error: non-zero (13) exit code from registry.access.redhat.com/dotnet/dotnet-20-rhel7@sha256:0dbafdca780475373a34be07877b152f94ff7ef4168758f1f9011bc71793245f_

Can someone help? thanks

**Comment by sriprasannafs** [comment]
Sorry. Will raise this in StackOverflow.

**Comment by tmds** [comment]
@sriprasannafs if you want, you can create an issue here: https://github.com/redhat-developer/s2i-dotnetcore. When you do, please provide some extra info like: what version of s2i-dotnetcore? Are you using the default assemble script? Can you provide a small project that reproduces the problem?

**Comment by alberttwong** [comment]
@sriprasannafs Actually you should raise this with Red Hat Support.   After all, you have a subscription to it.
