### ISSUE TITLE
I do not know what caused the build to fail.

### ISSUE THREAD

**Issue by kyunggyuyeol** [openshift-s2i/s2i-aspnet-example#39]
I make restfulapi with dotnet core 2.0 in visual studio 2017 and tested it with minishift. However, the build fails.

Is there a way to use the service with the git address, as in this example?

I also refer to the following example. But the build fails.
https://blog.openshift.com/announcing-net-core-2-0-support-openshift/

The git address you are trying to build. I do not know what caused the build to fail.
https://github.com/kyunggyuyeol/apitest

**Comment by aslicerh** [comment]
Hi @kyunggyuyeol 

Can you clarify how you're interacting with minishift? And did you add the imagestream at https://github.com/redhat-developer/s2i-dotnetcore.

And, just to add, I cloned and built your linked project in the same container that minishift should be using, and it seemed to build fine. That would point me to making sure that minishift is configured correctly to build your project.

**Comment by aslicerh** [comment]
@kyunggyuyeol Just checking in to see if you have an update to this issue.
