### ISSUE TITLE
build error on OpenShift 4.5 with .net template

### ISSUE THREAD

**Issue by rbaumgar** [openshift-s2i/s2i-aspnet-example#53]
when I build this sample I get following error
STEP 8: RUN /usr/libexec/s2i/assemble
---> Installing application source...
error: DOTNET_STARTUP_PROJECT has no project file
You can specify the startup project by adding an '.s2i/environment' file to the source repository.
The source repository contains the following projects:
- app/app.csproj
Update the '.s2i/environment' file to specify the project you want to publish, for example DOTNET_STARTUP_PROJECT=app/app.csproj.
subprocess exited with status 1
subprocess exited with status 1
error: build error: error building at STEP "RUN /usr/libexec/s2i/assemble": exit status 1

oc new-app dotnet:3.1~https://github.com/redhat-developer/s2i-dotnetcore-ex#dotnetcore-3.1 --context-dir app
works!

reason:
context-dir is set! not explicitly mentioned in ReadMe...

**Comment by tmds** [comment]
> oc new-app dotnet:3.1~https://github.com/redhat-developer/s2i-dotnetcore-ex#dotnetcore-3.1 --context-dir app
works!

This is what we have in the README.

[In the docs](https://access.redhat.com/documentation/en-us/net/3.1/html/getting_started_with_.net_on_rhel_8/using_net_core_3_1_on_openshift_container_platform#deploying-applications-from-source_using-dotnet-on-openshift-container-platform) we have:

> $ oc new-app --name=example-app 'dotnet:3.1~https://github.com/redhat-developer/s2i-dotnetcore-ex#dotnetcore-3.1' --build-env DOTNET_STARTUP_PROJECT=app

> not explicitly mentioned in ReadMe...

Where is it not explicitly mentioned?

**Comment by rbaumgar** [comment]
https://github.com/redhat-developer/s2i-dotnetcore-ex/blob/dotnetcore-3.1/README.adoc

**Comment by tmds** [comment]
> https://github.com/redhat-developer/s2i-dotnetcore-ex/blob/dotnetcore-3.1/README.adoc

This has: ` --context-dir app`.

**Comment by rbaumgar** [comment]
I tried it again and failed.
OpenShift 4.6
Login
create new project demo
go to developer console
add from Developer Catalog
select . Net Core Example - Template(!), change .net builder from dotnet:3.0 to dotnet:3.1. dotnet:3.0 does not exist.
go
```
Cloning "https://github.com/redhat-developer/s2i-dotnetcore-ex.git" ...
	Commit:	ed0f618681a8a2cc0cd33fab6043e8afb1f622bd (3.0: replace app with 'dotnet new mvc --no-restore' (#45))
	Author:	Tom Deseyn <tom.deseyn@gmail.com>
	Date:	Tue Sep 24 14:16:00 2019 +0200
Caching blobs under "/var/cache/blobs".
Getting image source signatures
Copying blob sha256:052baad69940cbd05bf4d96c1294ece0f7a46d51feec6ddb433484ad02890256
Copying blob sha256:1b8dabac56ed728c17a670d327474ab87dc392dc17721854ea599a7753326579
Copying blob sha256:37bc9f2a67ce21d557f8cecf46b5d6d58e41d033f994f42a5fbbdd070dbf48d6
Copying blob sha256:6500ac87b29ffd00c8655be65a6824dfcf9fc0accc625158ef1060bcedc84ca8
Copying config sha256:07a165c89dfd5d036622a006d4152a7730ec501ff2d6ae5947e29ed48e3491ac
Writing manifest to image destination
Storing signatures
Generating dockerfile with builder image image-registry.openshift-image-registry.svc:5000/openshift/dotnet@sha256:3c069d99548b81587e8d90dbd19e950f07bbb05cfd19d35c8efcdabe4c57c821
STEP 1: FROM image-registry.openshift-image-registry.svc:5000/openshift/dotnet@sha256:3c069d99548b81587e8d90dbd19e950f07bbb05cfd19d35c8efcdabe4c57c821
STEP 2: LABEL "io.openshift.build.commit.date"="Tue Sep 24 14:16:00 2019 +0200"       "io.openshift.build.commit.id"="ed0f618681a8a2cc0cd33fab6043e8afb1f622bd"       "io.openshift.build.commit.ref"="dotnetcore-3.0"       "io.openshift.build.commit.message"="3.0: replace app with 'dotnet new mvc --no-restore' (#45)"       "io.openshift.build.source-location"="https://github.com/redhat-developer/s2i-dotnetcore-ex.git"       "io.openshift.build.image"="image-registry.openshift-image-registry.svc:5000/openshift/dotnet@sha256:3c069d99548b81587e8d90dbd19e950f07bbb05cfd19d35c8efcdabe4c57c821"       "io.openshift.build.commit.author"="Tom Deseyn <tom.deseyn@gmail.com>"
STEP 3: ENV OPENSHIFT_BUILD_NAME="dotnet-example-1"     OPENSHIFT_BUILD_NAMESPACE="demo"     OPENSHIFT_BUILD_SOURCE="https://github.com/redhat-developer/s2i-dotnetcore-ex.git"     OPENSHIFT_BUILD_REFERENCE="dotnetcore-3.0"     OPENSHIFT_BUILD_COMMIT="ed0f618681a8a2cc0cd33fab6043e8afb1f622bd"     DOTNET_STARTUP_PROJECT="app"     DOTNET_ASSEMBLY_NAME=""     DOTNET_NPM_TOOLS=""     DOTNET_TEST_PROJECTS=""     DOTNET_CONFIGURATION="Release"     DOTNET_RESTORE_SOURCES=""     DOTNET_TOOLS=""     DOTNET_PUBLISH_READYTORUN=""     DOTNET_RESTORE_CONFIGFILE=""
STEP 4: USER root
STEP 5: COPY upload/src /tmp/src
STEP 6: RUN chown -R 1001:0 /tmp/src
STEP 7: USER 1001
STEP 8: RUN /usr/libexec/s2i/assemble
---> Installing application source...
Using SDK: 3.1.110
---> Restoring application dependencies...
  Restore completed in 1.32 sec for /opt/app-root/src/app/app.csproj.
---> Publishing application...
Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/usr/lib64/dotnet/sdk/3.1.110/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(234,5): error NETSDK1005: Assets file '/opt/app-root/src/app/obj/project.assets.json' doesn't have a target for '.NETCoreApp,Version=v3.1'. Ensure that restore has run and that you have included 'netcoreapp3.1' in the TargetFrameworks for your project. [/opt/app-root/src/app/app.csproj]
subprocess exited with status 1
subprocess exited with status 1
error: build error: error building at STEP "RUN /usr/libexec/s2i/assemble": exit status 1
```

**Comment by tmds** [comment]
> select . Net Core Example - Template(!), change .net builder from dotnet:3.0 to dotnet:3.1. dotnet:3.0 does not exist.

This template is no longer maintained (last working version was for 3.0) and it will not be part of new versions of OpenShift.

If you use Add > Samples > .NET Core, you should get a working app based on this repo.

**Comment by rbaumgar** [comment]
How will the templates remove? 
My cluster is setup with 4.5 and updated to 4.6. Sample Operator is running and template is still available...
How do customers and I get notified that the template is no longer maintained?

**Comment by tmds** [comment]
The template should no longer be included in future versions of OpenShift due to https://github.com/openshift/library/pull/250.
I don't know how that affects existing installations that are upgraded.

The template fails now because .NET Core 3.0 is EOL.
It can still be used. Also with s2i-dotnetcore-ex repo for 3.1, when you also set CONTEXT_DIR/DOTNET_STARTUP_PROJECT.

With this repo we want to reflect real usage of s2i-dotnetcore which almost always requires setting these variables.

The reason we're no longer updating the templates is OpenShift team recommended us to no longer provide templates that are not adding much.

Without the template, the example application can still be created using the _Create Sample_ workflow in OpenShift.

**Comment by tmds** [comment]
I'm going to close this. I appreciate your feedback to have good UX when using .NET Core on OpenShift.

Using Create Sample is the recommended way. It also works for every .NET Core version that is available.
