### ISSUE TITLE
We ask for HTTPS redirect but this sample is generally run in an non-HTTPS context

### ISSUE THREAD

**Issue by omajid** [openshift-s2i/s2i-aspnet-example#59]
This sample is meant to be used with the default OpenShift templates and dockerfiles

The default dockerfile disables HTTPS:
https://github.com/redhat-developer/s2i-dotnetcore/blob/b62a80dc2398adde5e80ef6ae0dfa0a40a2ec6c1/5.0/runtime/Dockerfile.rhel8#L36-L38

Perhaps we should disable asking for HTTPS redirect in our application too?

https://github.com/redhat-developer/s2i-dotnetcore-ex/blob/878f2600b9c6ad03f4fe4dbfd87874bb08affc61/app/Startup.cs#L42

**Comment by tmds** [comment]
This line comes from the mvc template. I think we should keep it because we don't expect our users to be removing this line either.
Closing the issue.
