### ISSUE TITLE
Why do all the examples use app.csproj when mvc generates dotnet.csproj?

### ISSUE THREAD

**Issue by cdrage** [openshift-s2i/s2i-aspnet-example#65]
So I'm using `odo` with the examples.

We take this example (s2i-dotnetcore-ex) for our usage with Devfile.

I'm curious why the files in this example are named `app.csproj` when dotnet generates `dotnet.csproj` ?

Shouldn't the default be `dotnet.csproj` so it aligns with how dotnet generates examples?

**Comment by tmds** [comment]
In practice, project files get named like .NET namespaces, so you'll have something like `MyCompany.Xyz.AbC.FrontEnd.csproj.

`app` is a nice short name and conveys the project is an application (and not a library).
